# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171205_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='NVH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to=b'NVH')),
            ],
        ),
    ]
